import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffe08f",
        "surface": "#fcf9f4",
        "tertiary-fixed-dim": "#e6c364",
        "surface-dim": "#dcdad5",
        "background": "#fcf9f4",
        "surface-bright": "#fcf9f4",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#adcebe",
        "secondary": "#755b00",
        "on-background": "#1c1c19",
        "secondary-fixed": "#ffe08f",
        "surface-tint": "#466558",
        "on-tertiary-fixed": "#241a00",
        "surface-container-highest": "#e5e2dd",
        "on-secondary-container": "#785d00",
        "on-secondary-fixed-variant": "#584400",
        "on-surface-variant": "#414845",
        "on-error-container": "#93000a",
        "inverse-surface": "#31302d",
        "surface-container-low": "#f6f3ee",
        "surface-container-high": "#ebe8e3",
        "tertiary": "#755b00",
        "on-primary-container": "#84a496",
        "primary-fixed-dim": "#adcebe",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c8c3",
        "on-primary": "#ffffff",
        "tertiary-container": "#c9a84c",
        "primary-container": "#1c3a2f",
        "error-container": "#ffdad6",
        "surface-container": "#f0ede9",
        "secondary-fixed-dim": "#e6c364",
        "secondary-container": "#fed977",
        "primary-fixed": "#c8eada",
        "on-surface": "#1c1c19",
        "on-tertiary-fixed-variant": "#584400",
        "on-error": "#ffffff",
        "surface-variant": "#e5e2dd",
        "on-secondary-fixed": "#241a00",
        "primary": "#05241a",
        "outline": "#727974",
        "on-tertiary-container": "#4f3d00",
        "on-primary-fixed-variant": "#2f4d41",
        "inverse-on-surface": "#f3f0eb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#012017"
      },
      fontFamily: {
        display: ['var(--font-playfair)', 'Playfair Display', 'serif'],
        headline: ['var(--font-noto-serif)', 'Noto Serif', 'serif'],
        body: ['var(--font-inter)', 'Inter', 'sans-serif'],
        label: ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
export default config
