import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e5c996",
        "surface": "#fcf9f4",
        "tertiary-fixed-dim": "#c7a56d",
        "surface-dim": "#dcdad5",
        "background": "#fcf9f4",
        "surface-bright": "#fcf9f4",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#adcebe",
        "secondary": "#6f5730",
        "on-background": "#1c1c19",
        "secondary-fixed": "#e5c996",
        "surface-tint": "#2d6349",
        "on-tertiary-fixed": "#2b1d0a",
        "surface-container-highest": "#e5e2dd",
        "on-secondary-container": "#6a4f1e",
        "on-secondary-fixed-variant": "#5f4920",
        "on-surface-variant": "#414845",
        "on-error-container": "#93000a",
        "inverse-surface": "#31302d",
        "surface-container-low": "#f6f3ee",
        "surface-container-high": "#ebe8e3",
        "tertiary": "#8b6b38",
        "on-primary-container": "#84a496",
        "primary-fixed-dim": "#adcebe",
        "on-secondary": "#ffffff",
        "outline-variant": "#c1c8c3",
        "on-primary": "#ffffff",
        "tertiary-container": "#b8975a",
        "primary-container": "#1c3a2f",
        "mid-green": "#2d6349",
        "error-container": "#ffdad6",
        "surface-container": "#f0ede9",
        "secondary-fixed-dim": "#c7a56d",
        "secondary-container": "#e7d1ac",
        "primary-fixed": "#c8eada",
        "on-surface": "#1c1c19",
        "on-tertiary-fixed-variant": "#5f4920",
        "on-error": "#ffffff",
        "surface-variant": "#e5e2dd",
        "on-secondary-fixed": "#241a00",
        "primary": "#05241a",
        "outline": "#727974",
        "on-tertiary-container": "#3d2a10",
        "on-primary-fixed-variant": "#2f4d41",
        "inverse-on-surface": "#f3f0eb",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#012017"
      },
      fontFamily: {
        display:  ['var(--font-display)', 'Cormorant', 'serif'],
        headline: ['var(--font-sans-ui)', 'Instrument Sans', 'sans-serif'],
        body:     ['var(--font-sans-ui)', 'Instrument Sans', 'sans-serif'],
        label:    ['var(--font-sans-ui)', 'Instrument Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
export default config
